/**
 * Post-build script to embed the IIFE content into a module
 * This is run after tsup builds both the IIFE and the main entry
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, '../dist');

// Read the built IIFE content
const iifeContent = readFileSync(join(distDir, 'client.iife.js'), 'utf-8');

// Encode as Base64 to prevent HTML parser issues (e.g. </script> tags or < characters)
const b64Content = Buffer.from(iifeContent).toString('base64');

// Generate the embedded module with a loader script
// The loader creates a Blob from the Base64 content and injects it via <script src="blob:...">
// This is CSP compliant (if blob: is allowed) and bypasses HTML parsing errors
const embeddedModule = `// Auto-generated - DO NOT EDIT
// This file is generated by scripts/embed-client.ts after build

/**
 * The Design Mode client script loader.
 * Injects the client via Base64 Blob to avoid syntax errors and CSP issues.
 */
export function getClientScript() {
    return \`(function() {
    try {
        var cls = "${b64Content}";
        var bin = atob(cls);
        var bytes = new Uint8Array(bin.length);
        for (var i = 0; i < bin.length; i++) {
            bytes[i] = bin.charCodeAt(i);
        }
        var blob = new Blob([bytes], { type: 'application/javascript' });
        var url = URL.createObjectURL(blob);
        var script = document.createElement('script');
        script.src = url;
        script.type = 'text/javascript';
        script.async = true;
        script.onload = function() { URL.revokeObjectURL(url); };
        script.onerror = function() { console.warn('[VibeSDK] Failed to load design mode script'); };
        document.head.appendChild(script);
        console.log('[VibeSDK] Design mode loader injected');
    } catch (e) {
        console.warn('[VibeSDK] Design mode loader failed:', e);
    }
})();\`;
}

/**
 * Legacy compatibility export (unused)
 */
export const CLIENT_SCRIPT = "Use getClientScript() instead";
`;

// Write to dist folder
writeFileSync(join(distDir, 'embedded.js'), embeddedModule);
writeFileSync(join(distDir, 'embedded.d.ts'), `export declare const CLIENT_SCRIPT: string;
export declare function getClientScript(): string;
`);

console.log('✅ Embedded client script generated (Base64 Loader)');
