/**
 * Post-build script to embed the IIFE content into a module
 * This is run after tsup builds both the IIFE and the main entry
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, '../dist');

// Read the built IIFE content
const iifeContent = readFileSync(join(distDir, 'client.iife.js'), 'utf-8');

// Generate the embedded module
const embeddedModule = `// Auto-generated - DO NOT EDIT
// This file is generated by scripts/embed-client.ts after build

/**
 * The minified Design Mode client script as a string.
 * Safe embedding using JSON.stringify.
 * Inject this into HTML by wrapping in a <script> tag.
 */
export const CLIENT_SCRIPT = ${JSON.stringify(iifeContent)};

/**
 * Get the client script as a string for injection into HTML.
 */
export function getClientScript() {
    return CLIENT_SCRIPT;
}
`;

// Write to dist folder
writeFileSync(join(distDir, 'embedded.js'), embeddedModule);
writeFileSync(join(distDir, 'embedded.d.ts'), `export declare const CLIENT_SCRIPT: string;
export declare function getClientScript(): string;
`);

console.log('✅ Embedded client script generated');
